name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set timestamp variable
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
    
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/cloud189-auto-save-tool:latest
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/cloud189-auto-save-tool:latest ${{ secrets.DOCKERHUB_USERNAME }}/cloud189-auto-save-tool:${{ env.TIMESTAMP }}
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push the Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/cloud189-auto-save-tool:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/cloud189-auto-save-tool:${{ env.TIMESTAMP }}
    
